### ISSUE TITLE
Presentacion del equipo

### ISSUE THREAD

**Issue by lucasde404** [lucasde404/ProyectoTeoria#1]
Presentación individual de cada miembro del equipo de trabajo.

**Comment by varelamatias7** [comment]
¡Hola!
Mi nombre es Varela Matías Oscar, soy de Catamarca y actualmente vivo en la provincia de Córdoba, Capital.
Este año comencé con la carrera de Desarrollo Web y Aplicaciones Digitales del ISPC. 
Inicie la carrera de Desarrollo, para entrar al mundo IT. Sin más que decir, les deseo los mejores éxitos a todos.

Saludos :)

**Comment by Aleejandra2022** [comment]
Hola 
Alejandra, estudio abogacia y empece este año con la carrera

**Comment by cristianmurua18** [comment]
Buenas, mi nombre es Christian Murua, este año empecé con la carrera de analista en computación en la FAMAF. Soy de Córdoba Capital con muchas ganas de aprender, tengo 30 años y la idea es poder aprender con el tiempo a programar y poder insertarme en el mercado. Vamos equipo que se puede!:

**Comment by LorevanBA** [comment]
Buenas, mi nombre es Lorena Vanesa Delgado, soy de Buenos Aires. Estoy en el área de Testing, y el año pasado comencé una tecnicatura en Desarrollo de Software. Me interesa aprender a desarrollar software tanto en su parte frontend como backend, por tal motivo este año comencé en en el ISPC para continuar aprendiendo y ampliando conocimientos. 
Apuesto a este equipo para hacer un buen proyecto y éxitos para todos!!!

**Comment by Vargas-Veronica** [comment]
Bienvenidos! Mi nombre es Veronica Vargas y estoy cursando primer año de la Tecnicatura en Desarrollo Web y Aplicaciones Digitales.
Actualmente me encuentro cursando conjuntamente Desarrollo Full Stack en Argentina Programa y Oracle Next Education.
También me interesa la parte de diseño, por lo que me encuentro terminando un intensivo de Diseño UX/UI en Codo a Codo.
Para las capacidades transversales , me encuentro realizando diferentes cursos de habilidades blandas en Accenture.
Mi idea es seguir capacitandome y poder insertarme en el mercado laboral.

**Comment by palomamontani** [comment]
Hola a todos!
Mi nombre es Paloma Montani, soy de Tandil, provincia de Buenos Aires, tengo 25 años y es mi primer año de la Tecnicatura y mi primer acercamiento con la programación y el mundo IT. Espero poder aprender mucho en ISPC y con este grupo!
Saludos!

**Comment by NicolasOrtiz7** [comment]
Hola! Mi nombre es Cristian Nicolás Ortiz. Soy de Buenos Aires, empecé con la programación en 2021 y  este año empecé con la Tecnicatura en Desarrollo Web y Aplicaciones digitales

**Comment by oscariote** [comment]
Hola a todos,soy Oscar Lujan,vivo en Cordoba Capital y aca estoy descubriendo este nuevo mundo para mi de la programacion.
