### ISSUE TITLE
Presentación Colaborador Edgardo Valle

### ISSUE THREAD

**Issue by lucasde404** [lucasde404/ProyectoTeoria#29]

**Comment by EtechFull** [comment]
Soy Edgardo Valle 
me gustaría poder colaborar en las presentaciones Sprint ya que me parece muy importante participar del aprendizage de estas poderosas herramientas de trabajo que son GIT y GITHUB, saludos

**Comment by EtechFull** [comment]
presentación Edgardo Valle

**Comment by EtechFull** [comment]
presentación Edgardo Valle
